# Import, Init

In [172]:
import os, sys
import pandas as pd
import seaborn as sns

sys.path.insert(0, "./classes/")
import cls_nnetwork

# reloading functions without runtime.restart
import importlib
importlib.reload(cls_nnetwork)

<module 'cls_nnetwork' from './classes/cls_nnetwork.py'>

In [173]:
# cut -- train test data with trimmed columns, so that it's more easy to train

nn_manager_cut = cls_nnetwork.NeuralManager(dir_path='../data/csv_to_train/train_test_cut')

>>> train-test inited:  {'X_test_cut': True, 'X_train_cut': True, 'y_test_cut': True, 'y_train_cut': True}


In [174]:
nn_manager_cut.X_train.shape, nn_manager_cut.X_test.shape

((3182, 12), (795, 12))

In [175]:
nn_manager_cut.X_train[:5]

Open    High     Low         Vol     AVBLS        NTRAT  \
Date                                                                    
2019-04-03  4859.3  5278.4  4814.0  13830000.0  1.248330  397961949.0   
2019-04-02  4145.1  4899.6  4143.5  14770000.0  1.215507  397560778.0   
2019-04-01  4102.3  4159.1  4076.8   3220000.0  1.205358  397191600.0   
2019-03-31  4111.8  4121.9  4082.2   2430000.0  1.173566  396808790.0   
2019-03-30  4103.7  4138.1  4057.1   2550000.0  1.204920  396430531.0   

                   TOUTV       TRFEE  BTC_MINED_PDAY  VOL_CHANGE_PDAY  \
Date                                                                    
2019-04-03  1.306792e+06  142.102988           425.0      -12780000.0   
2019-04-02  3.429199e+06  114.489789          1512.5        -940000.0   
2019-04-01  1.744093e+06   61.846737          2162.5       11550000.0   
2019-03-31  9.168389e+05   44.614255          1425.0         790000.0   
2019-03-30  9.228557e+05   54.673729          2050.0        -120000.0   

            MWNUS_CH_PDAY  NTRAT_CH_PDAY  
Date                                      
2019-04-03        52351.0       360333.0  
2019-04-02        61873.0       401171.0  
2019-04-01        87465.0       369178.0  
2019-03-31        34688.0       382810.0  
2019-03-30        64109.0       378259.0

## Normalizing

In [176]:
from sklearn.preprocessing import RobustScaler

nn_manager_cut.normalize_X(scaler=RobustScaler)

nn_manager_cut.X_train_normalized[:2]

array([[ 4.52988659e+00,  4.78975360e+00,  4.74139303e+00,
         1.74639067e+02,  1.29200649e+00,  1.87564906e+00,
         1.23854073e-01,  3.30862295e+00, -4.16368286e-01,
        -4.19170152e+02,  2.96856492e+00,  1.36703957e+00],
       [ 3.81150200e+00,  4.42010246e+00,  4.03002493e+00,
         1.86548731e+02,  1.24667529e+00,  1.87347194e+00,
         1.72651774e+00,  2.53817428e+00, -2.38363171e-01,
        -3.08142681e+01,  3.56691540e+00,  1.54784809e+00]])

## Splitting data to sequences

In [177]:
nn_manager_cut.split_X_to_sequencees(sequence_len=4)

In [178]:
nn_manager_cut.X_test_unrolled[0]

array([[ 3.53689240e+01,  3.51928763e+01,  3.72144714e+01,
         6.43691996e-01,  8.78219500e-01,  3.22867247e+00,
         4.83528350e-01, -2.62732657e-02, -3.42710997e-01,
        -1.29561296e-01,  2.21669940e+00,  6.36455909e-01],
       [ 3.66991727e+01,  3.66113686e+01,  3.65890404e+01,
         7.00706344e-01,  1.06493891e+00,  3.22761248e+00,
        -2.85041974e-01,  1.70764865e-01, -3.42710997e-01,
        -1.29561296e-01,  2.21669940e+00,  6.36455909e-01],
       [ 3.90631428e+01,  3.79461332e+01,  3.74674023e+01,
         1.03303665e+00,  1.34978675e+00,  3.22633882e+00,
        -8.60041445e-02,  5.25127690e-01, -3.41687980e-01,
        -8.42312423e-01,  1.90828686e+00,  8.10769348e-01],
       [ 3.74178590e+01,  3.81480361e+01,  3.90945838e+01,
         7.63548826e-01,  1.35460228e+00,  3.22495080e+00,
         6.05842104e-02,  7.35483801e-01, -3.57033248e-01,
         7.15703157e-01,  3.41691933e+00,  9.04069166e-01]])

In [179]:
# goes up by one sequence
nn_manager_cut.X_test_unrolled[1]

array([[ 3.66991727e+01,  3.66113686e+01,  3.65890404e+01,
         7.00706344e-01,  1.06493891e+00,  3.22761248e+00,
        -2.85041974e-01,  1.70764865e-01, -3.42710997e-01,
        -1.29561296e-01,  2.21669940e+00,  6.36455909e-01],
       [ 3.90631428e+01,  3.79461332e+01,  3.74674023e+01,
         1.03303665e+00,  1.34978675e+00,  3.22633882e+00,
        -8.60041445e-02,  5.25127690e-01, -3.41687980e-01,
        -8.42312423e-01,  1.90828686e+00,  8.10769348e-01],
       [ 3.74178590e+01,  3.81480361e+01,  3.90945838e+01,
         7.63548826e-01,  1.35460228e+00,  3.22495080e+00,
         6.05842104e-02,  7.35483801e-01, -3.57033248e-01,
         7.15703157e-01,  3.41691933e+00,  9.04069166e-01],
       [ 3.65447733e+01,  3.69161259e+01,  3.78081799e+01,
         6.42551709e-01,  1.35107044e+00,  3.22358723e+00,
         7.93558608e-03,  7.70429879e-01, -3.59079284e-01,
         3.31283313e-01,  6.84514963e+00,  8.84127896e-01]])

# Model 

## Model Combining

In [180]:
nn_manager_cut.X_train.shape[1]

12

In [181]:
from tensorflow.keras.layers import TimeDistributed 
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, LSTM, Dense

n_features = nn_manager_cut.X_train.shape[1]
n_seq = 2
n_steps = 2
conv1D_params = dict(filters=64, kernel_size=1, activation='relu')

template = [
    TimeDistributed(Conv1D(**conv1D_params), input_shape=(None, n_steps, n_features)),
    TimeDistributed(MaxPooling1D(pool_size=2)),
    TimeDistributed(Flatten()),
    LSTM(50, activation='relu'),
    Dense(1)
]

In [182]:
nn_manager_cut.model_combine(template=template)

>>> model compiled
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
time_distributed_15 (TimeDis (None, None, 2, 64)       832       
_________________________________________________________________
time_distributed_16 (TimeDis (None, None, 1, 64)       0         
_________________________________________________________________
time_distributed_17 (TimeDis (None, None, 64)          0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 50)                23000     
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 51        
Total params: 23,883
Trainable params: 23,883
Non-trainable params: 0
_________________________________________________________________


True

## Model Training

In [183]:
x_train = nn_manager_cut.X_train_unrolled 
y_train = nn_manager_cut.y_train_unrolled
x_train = x_train.reshape(x_train.shape[0], n_seq, n_steps, n_features)

x_test = nn_manager_cut.X_test_unrolled 
y_test = nn_manager_cut.y_test_unrolled
x_test = x_test.reshape(x_test.shape[0], n_seq, n_steps, n_features)

nn_manager_cut.model.fit(
    x=x_train, y=y_train,
    epochs= 5,
#     batch_size = 32,
    validation_data = (x_test, y_test),
    verbose = 2
)

Epoch 1/5
100/100 - 3s - loss: 10865791.0000 - mae: 1569.4956 - val_loss: 477315744.0000 - val_mae: 15857.2842
Epoch 2/5
100/100 - 1s - loss: 5128633.0000 - mae: 970.4158 - val_loss: 140662320.0000 - val_mae: 7709.2666
Epoch 3/5
100/100 - 1s - loss: 1437366.2500 - mae: 523.9120 - val_loss: 49534968.0000 - val_mae: 4350.4268
Epoch 4/5
100/100 - 1s - loss: 390443.6562 - mae: 251.8428 - val_loss: 10114601.0000 - val_mae: 1743.2034
Epoch 5/5
100/100 - 1s - loss: 106540.3047 - mae: 146.8750 - val_loss: 4536359.5000 - val_mae: 1127.0667
