# Import, Init

In [18]:
import os, sys
import pandas as pd
import seaborn as sns

sys.path.insert(0, "./classes/")
import cls_nnetwork

# reloading functions without runtime.restart
import importlib
importlib.reload(cls_nnetwork)

<module 'cls_nnetwork' from './classes/cls_nnetwork.py'>

In [19]:
# cut -- train test data with trimmed columns, so that it's more easy to train

nn_manager_cut = cls_nnetwork.NeuralManager(dir_path='../data/csv_to_train/train_test_cut')

>>> train-test inited:  {'X_test_cut': True, 'X_train_cut': True, 'y_test_cut': True, 'y_train_cut': True}


In [20]:
nn_manager_cut.X_train.shape, nn_manager_cut.X_test.shape

((3182, 12), (795, 12))

In [21]:
nn_manager_cut.X_train[:5]

Open    High     Low         Vol     AVBLS        NTRAT  \
Date                                                                    
2019-04-03  4859.3  5278.4  4814.0  13830000.0  1.248330  397961949.0   
2019-04-02  4145.1  4899.6  4143.5  14770000.0  1.215507  397560778.0   
2019-04-01  4102.3  4159.1  4076.8   3220000.0  1.205358  397191600.0   
2019-03-31  4111.8  4121.9  4082.2   2430000.0  1.173566  396808790.0   
2019-03-30  4103.7  4138.1  4057.1   2550000.0  1.204920  396430531.0   

                   TOUTV       TRFEE  BTC_MINED_PDAY  VOL_CHANGE_PDAY  \
Date                                                                    
2019-04-03  1.306792e+06  142.102988           425.0      -12780000.0   
2019-04-02  3.429199e+06  114.489789          1512.5        -940000.0   
2019-04-01  1.744093e+06   61.846737          2162.5       11550000.0   
2019-03-31  9.168389e+05   44.614255          1425.0         790000.0   
2019-03-30  9.228557e+05   54.673729          2050.0        -120000.0   

            MWNUS_CH_PDAY  NTRAT_CH_PDAY  
Date                                      
2019-04-03        52351.0       360333.0  
2019-04-02        61873.0       401171.0  
2019-04-01        87465.0       369178.0  
2019-03-31        34688.0       382810.0  
2019-03-30        64109.0       378259.0

## Normalizing

In [22]:
from sklearn.preprocessing import RobustScaler

nn_manager_cut.normalize_X(scaler=RobustScaler)

nn_manager_cut.X_train_normalized[:2]

array([[ 4.52988659e+00,  4.78975360e+00,  4.74139303e+00,
         1.74639067e+02,  1.29200649e+00,  1.87564906e+00,
         1.23854073e-01,  3.30862295e+00, -4.16368286e-01,
        -4.19170152e+02,  2.96856492e+00,  1.36703957e+00],
       [ 3.81150200e+00,  4.42010246e+00,  4.03002493e+00,
         1.86548731e+02,  1.24667529e+00,  1.87347194e+00,
         1.72651774e+00,  2.53817428e+00, -2.38363171e-01,
        -3.08142681e+01,  3.56691540e+00,  1.54784809e+00]])

## Splitting data to sequences

In [31]:
nn_manager_cut.split_X_to_sequencees(sequence_len=6)

In [34]:
nn_manager_cut.X_test_unrolled[0]

array([[ 3.53689240e+01,  3.51928763e+01,  3.72144714e+01,
         6.43691996e-01,  8.78219500e-01,  3.22867247e+00,
         4.83528350e-01, -2.62732657e-02, -3.42710997e-01,
        -1.29561296e-01,  2.21669940e+00,  6.36455909e-01],
       [ 3.66991727e+01,  3.66113686e+01,  3.65890404e+01,
         7.00706344e-01,  1.06493891e+00,  3.22761248e+00,
        -2.85041974e-01,  1.70764865e-01, -3.42710997e-01,
        -1.29561296e-01,  2.21669940e+00,  6.36455909e-01],
       [ 3.90631428e+01,  3.79461332e+01,  3.74674023e+01,
         1.03303665e+00,  1.34978675e+00,  3.22633882e+00,
        -8.60041445e-02,  5.25127690e-01, -3.41687980e-01,
        -8.42312423e-01,  1.90828686e+00,  8.10769348e-01],
       [ 3.74178590e+01,  3.81480361e+01,  3.90945838e+01,
         7.63548826e-01,  1.35460228e+00,  3.22495080e+00,
         6.05842104e-02,  7.35483801e-01, -3.57033248e-01,
         7.15703157e-01,  3.41691933e+00,  9.04069166e-01],
       [ 3.65447733e+01,  3.69161259e+01,  3.7808179

In [35]:
# goes up by one sequence
nn_manager_cut.X_test_unrolled[1]

array([[ 3.66991727e+01,  3.66113686e+01,  3.65890404e+01,
         7.00706344e-01,  1.06493891e+00,  3.22761248e+00,
        -2.85041974e-01,  1.70764865e-01, -3.42710997e-01,
        -1.29561296e-01,  2.21669940e+00,  6.36455909e-01],
       [ 3.90631428e+01,  3.79461332e+01,  3.74674023e+01,
         1.03303665e+00,  1.34978675e+00,  3.22633882e+00,
        -8.60041445e-02,  5.25127690e-01, -3.41687980e-01,
        -8.42312423e-01,  1.90828686e+00,  8.10769348e-01],
       [ 3.74178590e+01,  3.81480361e+01,  3.90945838e+01,
         7.63548826e-01,  1.35460228e+00,  3.22495080e+00,
         6.05842104e-02,  7.35483801e-01, -3.57033248e-01,
         7.15703157e-01,  3.41691933e+00,  9.04069166e-01],
       [ 3.65447733e+01,  3.69161259e+01,  3.78081799e+01,
         6.42551709e-01,  1.35107044e+00,  3.22358723e+00,
         7.93558608e-03,  7.70429879e-01, -3.59079284e-01,
         3.31283313e-01,  6.84514963e+00,  8.84127896e-01],
       [ 3.71549275e+01,  3.65749695e+01,  3.7555249

In [36]:
shape = nn_manager_cut.X_train_unrolled.shape
shape, shape[0]*shape[1]*shape[2]

((3176, 6, 12), 228672)

# Model 

## Model Combining

In [27]:
nn_manager_cut.X_train.shape[1]

12

[n_seq-n_steps in MLM example elaboration](z_MlMastery%20LSTM%20for%20TS%20.ipynb#n_seq-n_steps)<br>
(We can parameterize this and define the number of subsequences as n_seq and the number of time steps per subsequence as n_steps. [[source]](https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/#:~:text=We%20can%20parameterize%20this%20and))

In [40]:
from tensorflow.keras.layers import TimeDistributed 
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, LSTM, Dense

n_steps_subseq = 2
n_seq = 3
n_features = nn_manager_cut.X_train.shape[1]

conv1D_params = dict(filters=64, kernel_size=1, activation='relu')

# src: 
# https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/#:~:text=A%20convolutional%20neural
template = [
    TimeDistributed(Conv1D(**conv1D_params), input_shape=(None, n_steps_subseq, n_features)),
    TimeDistributed(MaxPooling1D(pool_size=2)),
    TimeDistributed(Flatten()),
    LSTM(50, activation='relu'),
    Dense(1)
]

In [41]:
nn_manager_cut.model_combine(template=template)

>>> model compiled
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
time_distributed_9 (TimeDist (None, None, 2, 64)       832       
_________________________________________________________________
time_distributed_10 (TimeDis (None, None, 1, 64)       0         
_________________________________________________________________
time_distributed_11 (TimeDis (None, None, 64)          0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 50)                23000     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51        
Total params: 23,883
Trainable params: 23,883
Non-trainable params: 0
_________________________________________________________________


True

## Model Training

In [46]:
%%timeit
res = nn_manager_cut.model_fit(n_epoch=30, n_seq=n_seq, n_steps=n_steps_subseq)

Epoch 1/30
100/100 - 1s - loss: 42721.1836 - mae: 68.1942 - val_loss: 1465678.0000 - val_mae: 758.4510
Epoch 2/30
100/100 - 1s - loss: 44598.9336 - mae: 71.4382 - val_loss: 1505349.8750 - val_mae: 666.6133
Epoch 3/30
100/100 - 1s - loss: 48321.4141 - mae: 74.9026 - val_loss: 2582349.0000 - val_mae: 852.2178
Epoch 4/30
100/100 - 1s - loss: 46196.6289 - mae: 71.7087 - val_loss: 2935627.2500 - val_mae: 921.4590
Epoch 5/30
100/100 - 1s - loss: 49100.7461 - mae: 76.4067 - val_loss: 2161624.2500 - val_mae: 773.0225
Epoch 6/30
100/100 - 1s - loss: 45470.6914 - mae: 71.2923 - val_loss: 1607973.3750 - val_mae: 692.7996
Epoch 7/30
100/100 - 1s - loss: 42962.1914 - mae: 67.7803 - val_loss: 1532980.6250 - val_mae: 661.9849
Epoch 8/30
100/100 - 1s - loss: 41973.0195 - mae: 67.2338 - val_loss: 1910113.5000 - val_mae: 734.7144
Epoch 9/30
100/100 - 1s - loss: 42903.0312 - mae: 69.4423 - val_loss: 1833224.2500 - val_mae: 721.7490
Epoch 10/30
100/100 - 1s - loss: 42633.8828 - mae: 67.5181 - val_loss: 14

100/100 - 1s - loss: 41190.6172 - mae: 65.6039 - val_loss: 1283499.1250 - val_mae: 606.2433
Epoch 21/30
100/100 - 1s - loss: 40926.6055 - mae: 66.0940 - val_loss: 1351365.0000 - val_mae: 619.4564
Epoch 22/30
100/100 - 1s - loss: 39155.5273 - mae: 63.0688 - val_loss: 1399986.0000 - val_mae: 627.1796
Epoch 23/30
100/100 - 1s - loss: 41918.8711 - mae: 67.5447 - val_loss: 1164637.2500 - val_mae: 610.9200
Epoch 24/30
100/100 - 1s - loss: 39736.6758 - mae: 64.3052 - val_loss: 1369563.5000 - val_mae: 621.5128
Epoch 25/30
100/100 - 1s - loss: 38873.8633 - mae: 62.7607 - val_loss: 1259853.5000 - val_mae: 602.6862
Epoch 26/30
100/100 - 1s - loss: 38438.6016 - mae: 61.9714 - val_loss: 1524210.2500 - val_mae: 668.8925
Epoch 27/30
100/100 - 1s - loss: 38974.1797 - mae: 62.9672 - val_loss: 1211449.2500 - val_mae: 593.7262
Epoch 28/30
100/100 - 1s - loss: 38783.3711 - mae: 62.6907 - val_loss: 1377638.3750 - val_mae: 621.4944
Epoch 29/30
100/100 - 1s - loss: 38238.1992 - mae: 61.1630 - val_loss: 12225

Epoch 10/30
100/100 - 1s - loss: 37642.3398 - mae: 60.6737 - val_loss: 1423319.1250 - val_mae: 647.9405
Epoch 11/30
100/100 - 1s - loss: 37122.5703 - mae: 59.7030 - val_loss: 1109398.2500 - val_mae: 571.3322
Epoch 12/30
100/100 - 1s - loss: 37310.7070 - mae: 60.5569 - val_loss: 1337016.7500 - val_mae: 622.0568
Epoch 13/30
100/100 - 1s - loss: 37128.3711 - mae: 60.5396 - val_loss: 1116180.2500 - val_mae: 567.8510
Epoch 14/30
100/100 - 1s - loss: 37481.7539 - mae: 60.7146 - val_loss: 1249949.5000 - val_mae: 599.1925
Epoch 15/30
100/100 - 1s - loss: 36820.5781 - mae: 59.4784 - val_loss: 1227394.2500 - val_mae: 593.4775
Epoch 16/30
100/100 - 1s - loss: 36592.3789 - mae: 58.8623 - val_loss: 1128852.2500 - val_mae: 570.3054
Epoch 17/30
100/100 - 1s - loss: 37128.3242 - mae: 59.7624 - val_loss: 1090907.8750 - val_mae: 593.2119
Epoch 18/30
100/100 - 1s - loss: 37350.4648 - mae: 60.5234 - val_loss: 1318325.5000 - val_mae: 614.7793
Epoch 19/30
100/100 - 1s - loss: 37079.5547 - mae: 60.1132 - val

Epoch 29/30
100/100 - 1s - loss: 37333.9453 - mae: 60.4997 - val_loss: 1143342.8750 - val_mae: 571.4907
Epoch 30/30
100/100 - 1s - loss: 36673.2305 - mae: 59.3914 - val_loss: 1059830.1250 - val_mae: 559.5101
19 s ± 170 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
